### ISSUE TITLE
Error 306

### ISSUE THREAD

**Issue by DanielaNye** [bcgov/permitify#117]
================================================================================
person_1           |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
person_1           |                                  Dload  Upload   Total   Spent    Left  Speed
100   173  100   130  100    43     34     11  0:00:03  0:00:03 --:--:--    34{"seed":"bc_registries_000000000000000000","did":"7VkdE3erBDJnrQMVbEnRzg","verkey":"4YLsvyVBs7qLYwYoDy6bTmxujFf1Kdx5jGuNM7jhdKjd"}
person_1           | Starting server ...
person_1           | INFO 2018-10-07 15:36:47,616 agent 1 140107237312256 acquiring lock for Issuer
person_1           | INFO 2018-10-07 15:36:47,616 agent 1 140107237312256 acquired lock for Issuer
person_1           | WARNING 2018-10-07 15:36:49,166 libindy 1 140107237312256 _indy_loop_callback: Function returned error 306
person_1           | INFO 2018-10-07 15:36:49,167 nodepool 1 140107237312256 Pool ledger config for permitify-issuer already exists
person_1           | WARNING 2018-10-07 15:36:49,682 libindy 1 140107237312256 _indy_loop_callback: Function returned error 203
person_1           | INFO 2018-10-07 15:36:49,682 wallet 1 140107237312256 Opening existing wallet: Gov ID Issuer Wallet
person_1           | INFO 2018-10-07 15:36:49,876 wallet 1 140107237312256 Opened wallet Gov ID Issuer Wallet on handle 3
person_1           | INFO 2018-10-07 15:36:50,473 agent 1 140107237312256 Issuer releasing lock
person_1           | DEBUG 2018-10-07 15:36:50,486 schema 1 140107237312256 
person_1           | ============================================================================

Can anyone help me solving this error please?

**Comment by swcurran** [comment]
It's hard to tell from just the error message what the problem.  Could you describe what part of the process you are doing when you encounter the error?  Thanks.

**Comment by DanielaNye** [comment]
I'm sorry i forgot to mention it, it appears when running ./manage start.

**Comment by cywolf** [comment]
It's this error, essentially: https://github.com/hyperledger/indy-sdk/blob/9e32bf35ba8d053ec53562511da60899013a2541/doc/how-tos/rotate-key/python/README.md#common-errors

It looks like it goes on to open the wallet though, so maybe just a warning?

**Comment by swcurran** [comment]
@DanielaNye - there is not enough information to help further than what was provided in the previous comment.  If you can provide more information, that might help, but closing for now.
