### ISSUE TITLE
Permitify 1.5 Epic - Deploy the current docker version of Permitify on OpenShift Dev and Test

### ISSUE THREAD

**Issue by swcurran** [bcgov/permitify#118]
Take the current docker version of Permitify and upgrade it to run on OpenShift Dev and then once it is operational, upgrade Test.  In doing that:

1. Make sure that either Dev or Test is ALWAYS available, and notify the team as the primary demo site is changed.
2. As appropriate, update the pre-loaded organization data to credential process to match the new credentials.
3. As appropriate, update or redeploy the BCovrin instance(s) that back the Permitify demo.

This effort will be called "Permitify 1.5" to avoid confusion with the work that Nick is doing that we're calling "Permitify 2.0".

**Comment by esune** [comment]
Opened PR: https://github.com/bcgov/permitify/pull/124

**Comment by WadeBarnes** [comment]
Updates have been reviewed and tested in DEV, PR merged.

**Comment by esune** [comment]
The new issue #126 will need to be tackled first, in order for TEST to be updated to the latest version and re-populated.
