### ISSUE TITLE
Update permitify schema and mapping to ensure TheOrgBook is being populated fully for the demo

### ISSUE THREAD

**Issue by nrempel** [bcgov/permitify#126]
TheOrgBook is populated from credentials using a mapping definition. Incoming credentials in TheOrgBook are parsed and the application database in TheOrgBook is updated.

The "foundational" credential is a credential is one that creates a "topic" in TheOrgBook. It also generates an organization page. Currently, the permitify uses a schema with a minimal set of attributes. It works, but some of the fields are left blank in TheOrgBook. See the following images:

permitify:
![Screen Shot 2018-10-29 at 3.46.50 PM.png](https://images.zenhubusercontent.com/5ae8a5ee4b5806bc2bd15a54/be02430f-bd96-4f8d-b4cb-cf7ba1ef3282)

real bc registries data from prod:
![Screen Shot 2018-10-29 at 3.48.00 PM.png](https://images.zenhubusercontent.com/5ae8a5ee4b5806bc2bd15a54/748f5ca2-0393-41da-bb7b-5e91807d5af4)

You can use the real bc registries von-x configuration as a starting point.

The schema is here: https://github.com/ianco/von-bc-registries-agent/blob/master/bcreg-x/config/schemas.yml

the mapping is here: https://github.com/ianco/von-bc-registries-agent/blob/master/bcreg-x/config/services.yml#L50

I recommend starting by trying to copy over the schema and mapping and changing only what is required if there are any problems.

**Comment by esune** [comment]
This is resolved by #128

**Comment by esune** [comment]
Fixed by #133
