### ISSUE TITLE
Update to `bcgovimages/von-image:1.6-ew-11*` images

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/permitify#138]
Update to `bcgovimages/von-image:1.6-ew-11*` images to pick up `von_anchor v1.6.37`.

A necessary 256-bit compliant encoder has been added to von_anchor, affecting credentials.  Unfortunately it is not backwardly compatible with older credentials so they will need to be reloaded.

Environments to update:
- [x] devex-von-permitify-dev
- [x] devex-von-permitify-test

**Comment by WadeBarnes** [comment]
Over to @esune to finish up the deployments.

**Comment by esune** [comment]
The last environment was successfully updated.
