### ISSUE TITLE
Update to `bcgovimages/von-image:1.6-ew-13*` images

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/permitify#148]
- Adds support for credential dependency look-up.
- Includes updated versions of von_anchor and von-x

Environments to update:
- [x] devex-von-permitify-dev
- [x] devex-von-permitify-test

**Comment by WadeBarnes** [comment]
Over to @esune, to update the `test` environment.

**Comment by esune** [comment]
The last environment was successfully updated.
