### ISSUE TITLE
OrgBook base url

### ISSUE THREAD

**Issue by shader** [bcgov/permitify#33]
Right now, the default value for THE_ORG_BOOK_BASE_URL is https://django-devex-von-dev.pathfinder.gov.bc.ca/api/v1.

Is this proper / acceptable behavior for use by random people trying out your demo? Will that mess with your test environment?

If not, what is the process for setting it up locally?

**Comment by WadeBarnes** [comment]
That's fine.  There are examples in the `manage` script (use `./manage -h`) to target a different server if you wish.  Such as running a docker compose instance of TheOrgBook.
