### ISSUE TITLE
Authorizing wallet seeds

### ISSUE THREAD

**Issue by shader** [bcgov/permitify#36]
I'm working on making a new issuer based on the example services, and they include a configuration line like the following:

https://github.com/bcgov/permitify/blob/83dd83e4137893e3909df3544b622431491b6db2/site_templates/bc_registries/config.toml#L10-L11

How does one authorize a seed on the ledger?

**Comment by nrempel** [comment]
If you are using our test ledger(determined by this file https://github.com/bcgov/permitify/blob/master/src/.genesis), you can go to our page and register it manually: http://138.197.170.136

We've included a helper.

When joining the real Sovrin network, this process is not so clear. We've talked to them about it and as far as I understand it, you must provide a trust anchor with your did and verkey and they will write the entity by some process.
