### ISSUE TITLE
von connector/agent

### ISSUE THREAD

**Issue by shader** [bcgov/permitify#37]
Just curious, but what is the relationship between the various versions and repositories containing von_connector and von_agent? They seem to exist in multiple places...

**Comment by swcurran** [comment]
This has been a bubbling question that we have been addressing in a variety of small ways.  We now have a roadmap for how the pieces are all named and connected.  If you are interested - see the Quick Start guide - https://github.com/bcgov/TheOrgBook/blob/master/docker/README.md#running-a-complete-provisional-von-network

This Google Doc shows what we have and are planning to do with the repos.

https://drive.google.com/open?id=1ITKyjMpwzp5NdOON2xP_3xsF4AuyPXK1mOIaQMqeVuU
